class CountryCode {
  final String name;
  final String nameAr;
  final String code;
  final String flag;
  final int minLength;
  final int maxLength;

  const CountryCode({
    required this.name,
    required this.nameAr,
    required this.code,
    required this.flag,
    required this.minLength,
    required this.maxLength,
  });
}

class CountryCodes {
  static const List<CountryCode> all = [
    // Arab Countries
    CountryCode(
      name: 'Saudi Arabia',
      nameAr: 'السعودية',
      code: '+966',
      flag: '🇸🇦',
      minLength: 9,
      maxLength: 9,
    ),
    CountryCode(
      name: 'United Arab Emirates',
      nameAr: 'الإمارات',
      code: '+971',
      flag: '🇦🇪',
      minLength: 9,
      maxLength: 9,
    ),
    CountryCode(
      name: 'Egypt',
      nameAr: 'مصر',
      code: '+20',
      flag: '🇪🇬',
      minLength: 10,
      maxLength: 10,
    ),
    CountryCode(
      name: 'Kuwait',
      nameAr: 'الكويت',
      code: '+965',
      flag: '🇰🇼',
      minLength: 8,
      maxLength: 8,
    ),
    CountryCode(
      name: 'Qatar',
      nameAr: 'قطر',
      code: '+974',
      flag: '🇶🇦',
      minLength: 8,
      maxLength: 8,
    ),
    CountryCode(
      name: 'Bahrain',
      nameAr: 'البحرين',
      code: '+973',
      flag: '🇧🇭',
      minLength: 8,
      maxLength: 8,
    ),
    CountryCode(
      name: 'Oman',
      nameAr: 'عمان',
      code: '+968',
      flag: '🇴🇲',
      minLength: 8,
      maxLength: 8,
    ),
    CountryCode(
      name: 'Jordan',
      nameAr: 'الأردن',
      code: '+962',
      flag: '🇯🇴',
      minLength: 9,
      maxLength: 9,
    ),
    CountryCode(
      name: 'Lebanon',
      nameAr: 'لبنان',
      code: '+961',
      flag: '🇱🇧',
      minLength: 8,
      maxLength: 8,
    ),
    CountryCode(
      name: 'Iraq',
      nameAr: 'العراق',
      code: '+964',
      flag: '🇮🇶',
      minLength: 10,
      maxLength: 10,
    ),
    CountryCode(
      name: 'Syria',
      nameAr: 'سوريا',
      code: '+963',
      flag: '🇸🇾',
      minLength: 9,
      maxLength: 9,
    ),
    CountryCode(
      name: 'Palestine',
      nameAr: 'فلسطين',
      code: '+970',
      flag: '🇵🇸',
      minLength: 9,
      maxLength: 9,
    ),
    CountryCode(
      name: 'Yemen',
      nameAr: 'اليمن',
      code: '+967',
      flag: '🇾🇪',
      minLength: 9,
      maxLength: 9,
    ),
    CountryCode(
      name: 'Libya',
      nameAr: 'ليبيا',
      code: '+218',
      flag: '🇱🇾',
      minLength: 10,
      maxLength: 10,
    ),
    CountryCode(
      name: 'Tunisia',
      nameAr: 'تونس',
      code: '+216',
      flag: '🇹🇳',
      minLength: 8,
      maxLength: 8,
    ),
    CountryCode(
      name: 'Algeria',
      nameAr: 'الجزائر',
      code: '+213',
      flag: '🇩🇿',
      minLength: 9,
      maxLength: 9,
    ),
    CountryCode(
      name: 'Morocco',
      nameAr: 'المغرب',
      code: '+212',
      flag: '🇲🇦',
      minLength: 9,
      maxLength: 9,
    ),
    CountryCode(
      name: 'Sudan',
      nameAr: 'السودان',
      code: '+249',
      flag: '🇸🇩',
      minLength: 9,
      maxLength: 9,
    ),
    CountryCode(
      name: 'Somalia',
      nameAr: 'الصومال',
      code: '+252',
      flag: '🇸🇴',
      minLength: 8,
      maxLength: 9,
    ),
    CountryCode(
      name: 'Mauritania',
      nameAr: 'موريتانيا',
      code: '+222',
      flag: '🇲🇷',
      minLength: 8,
      maxLength: 8,
    ),
    CountryCode(
      name: 'Djibouti',
      nameAr: 'جيبوتي',
      code: '+253',
      flag: '🇩🇯',
      minLength: 8,
      maxLength: 8,
    ),
    CountryCode(
      name: 'Comoros',
      nameAr: 'جزر القمر',
      code: '+269',
      flag: '🇰🇲',
      minLength: 7,
      maxLength: 7,
    ),
    
    // Major International Countries
    CountryCode(
      name: 'United States',
      nameAr: 'الولايات المتحدة',
      code: '+1',
      flag: '🇺🇸',
      minLength: 10,
      maxLength: 10,
    ),
    CountryCode(
      name: 'United Kingdom',
      nameAr: 'المملكة المتحدة',
      code: '+44',
      flag: '🇬🇧',
      minLength: 10,
      maxLength: 10,
    ),
    CountryCode(
      name: 'Canada',
      nameAr: 'كندا',
      code: '+1',
      flag: '🇨🇦',
      minLength: 10,
      maxLength: 10,
    ),
    CountryCode(
      name: 'France',
      nameAr: 'فرنسا',
      code: '+33',
      flag: '🇫🇷',
      minLength: 9,
      maxLength: 9,
    ),
    CountryCode(
      name: 'Germany',
      nameAr: 'ألمانيا',
      code: '+49',
      flag: '🇩🇪',
      minLength: 10,
      maxLength: 11,
    ),
    CountryCode(
      name: 'Italy',
      nameAr: 'إيطاليا',
      code: '+39',
      flag: '🇮🇹',
      minLength: 10,
      maxLength: 10,
    ),
    CountryCode(
      name: 'Spain',
      nameAr: 'إسبانيا',
      code: '+34',
      flag: '🇪🇸',
      minLength: 9,
      maxLength: 9,
    ),
    CountryCode(
      name: 'Turkey',
      nameAr: 'تركيا',
      code: '+90',
      flag: '🇹🇷',
      minLength: 10,
      maxLength: 10,
    ),
    CountryCode(
      name: 'India',
      nameAr: 'الهند',
      code: '+91',
      flag: '🇮🇳',
      minLength: 10,
      maxLength: 10,
    ),
    CountryCode(
      name: 'Pakistan',
      nameAr: 'باكستان',
      code: '+92',
      flag: '🇵🇰',
      minLength: 10,
      maxLength: 10,
    ),
    CountryCode(
      name: 'Bangladesh',
      nameAr: 'بنغلاديش',
      code: '+880',
      flag: '🇧🇩',
      minLength: 10,
      maxLength: 10,
    ),
    CountryCode(
      name: 'Indonesia',
      nameAr: 'إندونيسيا',
      code: '+62',
      flag: '🇮🇩',
      minLength: 10,
      maxLength: 12,
    ),
    CountryCode(
      name: 'Malaysia',
      nameAr: 'ماليزيا',
      code: '+60',
      flag: '🇲🇾',
      minLength: 9,
      maxLength: 10,
    ),
    CountryCode(
      name: 'China',
      nameAr: 'الصين',
      code: '+86',
      flag: '🇨🇳',
      minLength: 11,
      maxLength: 11,
    ),
    CountryCode(
      name: 'Japan',
      nameAr: 'اليابان',
      code: '+81',
      flag: '🇯🇵',
      minLength: 10,
      maxLength: 10,
    ),
    CountryCode(
      name: 'South Korea',
      nameAr: 'كوريا الجنوبية',
      code: '+82',
      flag: '🇰🇷',
      minLength: 10,
      maxLength: 11,
    ),
    CountryCode(
      name: 'Australia',
      nameAr: 'أستراليا',
      code: '+61',
      flag: '🇦🇺',
      minLength: 9,
      maxLength: 9,
    ),
    CountryCode(
      name: 'Brazil',
      nameAr: 'البرازيل',
      code: '+55',
      flag: '🇧🇷',
      minLength: 11,
      maxLength: 11,
    ),
    CountryCode(
      name: 'Russia',
      nameAr: 'روسيا',
      code: '+7',
      flag: '🇷🇺',
      minLength: 10,
      maxLength: 10,
    ),
    CountryCode(
      name: 'South Africa',
      nameAr: 'جنوب أفريقيا',
      code: '+27',
      flag: '🇿🇦',
      minLength: 9,
      maxLength: 9,
    ),
  ];

  static CountryCode get defaultCountry => all.first; // Saudi Arabia
}
